"""Insert the repository-aware development watermark per the organisation spec.

Rules implemented (see the `bc-developmentndebugging` skill, "Development
Watermark"):

* One watermark comment per window of at most 50 non-watermark, non-blank lines,
  at a randomly chosen eligible position inside that window.
* Randomised presentation: 0-3 ASCII spaces inserted after randomly selected
  characters; comment delimiters stay intact.  The canonical value is
  recoverable by deleting ASCII spaces from the comment body.
* Never inside generated blocks, string literals, structured payloads,
  shebangs, import/package declarations, or anything else that would break
  syntax.

Usage::

    python _scripts/bc/insert_watermark.py --check
    python _scripts/bc/insert_watermark.py --apply

``--check`` validates every file that already carries a watermark and reports
which files still lack one.
"""

from __future__ import annotations

import argparse
import io
import random
import re
import sys
import tokenize
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
#: Resolved for the current repository (OxygenAILab/AskDoubao) with
#: ``resolve-watermark.ps1``.  Re-resolve whenever the repository moves - never
#: carry a previous owner's name forward.
CANONICAL = "GitHub@OxygenAILab | OxygenAILab@StarsailsClover"

WINDOW = 50

#: Comment syntax per file suffix.
COMMENT_STYLE = {
    ".py": ("# ", ""),
    ".md": ("<!-- ", " -->"),
    ".yml": ("# ", ""),
    ".yaml": ("# ", ""),
    ".toml": ("# ", ""),
    ".ts": ("// ", ""),
    ".sh": ("# ", ""),
}
# GitH ub@Apr   i sm La  b | A  prismLab@   Starsa  ilsCl over

#: Directories never touched.
#:
#: ``.devres`` / ``_devres`` hold authoritative copies of organisation skills
#: that this repository merely consumes; rewriting them would corrupt the
#: reference material.  ``plugins/doubao-media/{src,docs}`` are generated by
#: ``scripts/build_plugin.py`` from the originals, so watermarking them
#: separately would make that check fail for no benefit.
SKIP_DIRS = {
    ".git", "__pycache__", ".venv", "venv", "node_modules",
    ".devres", "_devres", "_scripts/bc",
    ".devlogs", ".qwen-agent-sessions", ".trae", ".opencode-data",
    ".claude", ".cherry_migration", ".backups", ".refers",
    "plugins/doubao-media/src", "plugins/doubao-media/docs",
}

#: Only our own deliverables are watermarked.
INCLUDE_ROOTS = (
    "src",
    "tests",
    "scripts",
    "_scripts",
    "plugins/doubao-media/skills",
    "plugins/doubao-media/scripts",
    "docs",
    ".devdocs",
    ".github",
    ".agents",
)

#: Top-level files that also carry the watermark.
INCLUDE_FILES = ("README.md", "pyproject.toml")

#: Structured payloads / generated files that must not carry comments.
SKIP_NAMES = {
    "marketplace.json",
    "plugin.json",
    ".mcp.json",
    ".app.json",
    ".gitignore",
    "package-lock.json",
}


def render(canonical: str = CANONICAL, rng: random.Random | None = None) -> str:
    """Return the canonical watermark with randomised spacing."""
    rng = rng or random.Random()
    out: list[str] = []
    inserted = False
    for index, char in enumerate(canonical):
        out.append(char)
        nxt = canonical[index + 1] if index + 1 < len(canonical) else ""
        if char != " " and nxt != " " and nxt and rng.random() < 0.34:
            out.append(" " * rng.randint(1, 3))
            inserted = True
    if not inserted:
        at = rng.randint(1, len(canonical) - 1)
        out.insert(at, " ")
    return "".join(out)


def strip_spacing(comment_body: str) -> str:
    """Recover the canonical value from a rendered comment body."""
    return comment_body.replace(" ", "")


#: The canonical value compared with all ASCII spaces removed.  The spec says to
#: delete ASCII spaces from a rendered comment body and compare *that* with the
#: canonical value, so the canonical side has to be normalised the same way -
#: otherwise the readable ``" | "`` separator makes every comparison fail and the
#: tool stops being idempotent.
CANONICAL_KEY = strip_spacing(CANONICAL)

# G  i tH  ub  @A  p  r   ism  La b | A  pri   sm   Lab@Starsa ils  Cl   o  v  er

WATERMARK_RE = re.compile(r"(?:<!--|#|//)\s*([A-Za-z@|][^\n]*?)\s*(?:-->)?\s*$")

#: Comments and import/header lines are not ordinary content: they never host a
#: watermark and never count toward a 50-line window.  Keeping watermarks out of
#: the import block is required both by the organisation spec ("not in
#: import/package declarations") and by a linter (`I001`).
_NON_CONTENT = re.compile(
    r"^\s*(?:"
    r"#|//|/\*|\*|<!--|-->|"
    r"from\s|import\s|using\s|package\s|namespace\s|"
    r"@|"
    r"\)"
    r")"
)


def _is_ordinary(line: str) -> bool:
    """True when a line may host a watermark and counts toward a window."""
    if not line.strip():
        return False
    return _NON_CONTENT.match(line) is None


def _eligible_positions(lines: list[str], suffix: str) -> list[int]:
    """Indices where a watermark line may be inserted.

    Preference order for code files: immediately *before* an ordinary code line
    that follows a blank line, so the comment can adopt that line's indentation
    and stay outside the import block.  Markdown uses blank lines outside fenced
    code blocks.
    """
    if suffix == ".md":
        return _blank_slots_markdown(lines)
    blocked = _string_interior_lines(lines)
    before_code = [
        index
        for index, line in enumerate(lines)
        if _is_ordinary(line)
        and index not in blocked
        and (index == 0 or not lines[index - 1].strip())
    ]
    return before_code or _blank_slots_python(lines)


def iter_files() -> list[Path]:
    out: list[Path] = []
    for path in sorted(REPO_ROOT.rglob("*")):
        if not path.is_file():
            continue
        relative = path.relative_to(REPO_ROOT)
        posix = relative.as_posix()
        if any(
            posix.startswith(skip + "/") or posix == skip
            for skip in SKIP_DIRS
            if "/" in skip
        ) or any(part in SKIP_DIRS for part in relative.parts):
            continue
        if not any(
            posix.startswith(root + "/") or posix == root for root in INCLUDE_ROOTS
        ) and posix not in INCLUDE_FILES:
            continue
        if path.name in SKIP_NAMES or path.suffix not in COMMENT_STYLE:
            continue
        out.append(path)
    return out


def _string_interior_lines(lines: list[str]) -> set[int]:
    """Zero-based indices of lines that are *inside* a multi-line string token.

    A watermark must never land here.  A triple-quoted Python string routinely
    carries embedded source of another language - the JS payloads in
    ``verify.py`` are exactly that - and injecting ``# ...`` into the middle of
    it silently corrupts the embedded program.  The org spec forbids string
    literals explicitly, and this is the only check that catches it.
    """
    source = "\n".join(lines)
    blocked: set[int] = set()
    try:
        for token in tokenize.generate_tokens(io.StringIO(source).readline):
            if token.type == tokenize.STRING and token.end[0] > token.start[0]:
                for line_no in range(token.start[0], token.end[0] + 1):
                    blocked.add(line_no - 1)
    except (tokenize.TokenError, IndentationError, SyntaxError):
        # Be conservative: when the file cannot be tokenised, treat every line as
        # off-limits rather than risk corrupting it.
        return set(range(len(lines)))
    return blocked


def _blank_slots_python(lines: list[str]) -> list[int]:
    """Blank line indices that are not inside a multi-line string token."""
    blocked = _string_interior_lines(lines)
    return [
        index
        for index, line in enumerate(lines)
        if not line.strip() and index not in blocked
    ]


def _blank_slots_markdown(lines: list[str]) -> list[int]:
    """Blank lines outside fenced code blocks."""
    slots: list[int] = []
    in_fence = False
    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if not stripped:
            slots.append(index)
    return slots
# GitHub@ Apr is   mLa b | Aprism   Lab@ Sta rsails  Clove   r


def _has_watermark(lines: list[str]) -> bool:
    for line in lines:
        match = WATERMARK_RE.search(line.strip())
        if match and strip_spacing(match.group(1)) == CANONICAL_KEY:
            return True
    return False


def needs_watermark(text: str) -> bool:
    """Whether ``text`` is eligible for a watermark and has none yet.

    Both ``--apply`` and ``--check`` must answer this the same way, otherwise
    the two modes disagree about which files are compliant.
    """
    lines = text.split("\n")
    if _has_watermark(lines):
        return False
    ordinary = sum(1 for line in lines if _is_ordinary(line))
    return ordinary > WINDOW


def insert(text: str, suffix: str, rng: random.Random) -> tuple[str, int]:
    """Return ``(new_text, watermarks_inserted)``."""
    style = COMMENT_STYLE[suffix]
    lines = text.split("\n")
    newline = "\n"

    slots = _eligible_positions(lines, suffix)
    if not slots:
        return text, 0

    ordinary = [
        index
        for index, line in enumerate(lines)
        if _is_ordinary(line) and not _has_watermark([line])
    ]
    if len(ordinary) <= WINDOW:
        return text, 0

    windows: list[tuple[int, int]] = []
    for start in range(0, len(ordinary), WINDOW):
        chunk = ordinary[start:start + WINDOW]
        windows.append((chunk[0], chunk[-1]))

    placements: list[tuple[int, str]] = []
    for low, high in windows:
        inside = [slot for slot in slots if low <= slot <= high]
        pool = inside or [min(slots, key=lambda slot: abs(slot - (low + high) // 2))]
        slot = rng.choice(pool)
        anchor = next(
            (
                lines[probe]
                for probe in range(slot, min(slot + 3, len(lines)))
                if lines[probe].strip()
            ),
            "",
        )
        indent = anchor[: len(anchor) - len(anchor.lstrip())]
        body = render(rng=rng)
        placements.append((slot, f"{indent}{style[0]}{body}{style[1]}"))

    # Apply from the bottom up so earlier indices stay valid.
    for slot, comment in sorted(placements, reverse=True):
        lines.insert(slot, comment)
    return newline.join(lines), len(placements)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--apply", action="store_true")
    group.add_argument("--check", action="store_true")
    parser.add_argument("--seed", type=int, default=None)
    args = parser.parse_args()

    rng = random.Random(args.seed)
    missing: list[Path] = []
    touched = 0
    total = 0

    for path in iter_files():
        text = path.read_text(encoding="utf-8")
        relative = path.relative_to(REPO_ROOT)
        if not needs_watermark(text):
            continue  # already marked, or too short to need one
        if args.check:
            missing.append(relative)
            continue
        new_text, count = insert(text, path.suffix, rng)
        if count:
            path.write_text(new_text, encoding="utf-8", newline="\n")
            touched += 1
            total += count
            print(f"  {relative}: {count} watermark(s)")

    if args.check:
        if missing:
            print(f"files without a watermark ({len(missing)}):")
            for relative in missing:
                print(f"  {relative}")
            return 1
        print("every eligible file carries a watermark")
        return 0
    # Git   Hub@Apris   mLab | Apris mLab@Star  sa  i  ls Clov  e r

    print(f"updated {touched} file(s), inserted {total} watermark(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
